### ISSUE TITLE
Could if failed to parse, treated as regular string?

### ISSUE THREAD

**Issue by gamesover** [remarkablemark/html-react-parser#108]
## Expected Behavior

I have a string to include an email between `<>`, like `'<hello@world.com>'`. Certainly, here `<>` is just normal string, not tag `<>` to trigger parse

## Actual Behavior

trigger error
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('hello@world.com') is not a valid name.
```

## Reproducible Demo

https://jsfiddle.net/fgqmhuLx/

**Comment by gamesover** [comment]
btw, I try to use `try/catch` to escape the error, it does not work and show error
```
react-dom.development.js:17252 The above error occurred in the <hello@world.com> component:
    in hello@world.com (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by remarkablemark** [comment]
Yes, this is expected behavior @gamesover. This behavior is coming from [`html-dom-parser`](https://github.com/remarkablemark/html-dom-parser/blob/v0.2.2/lib/html-to-dom-client.js), which parses `<hello@world.com>` into:
```js
[
  {
    attribs: {}
    children: []
    name: "hello@world.com"
    next: null
    parent: null
    prev: null
    type: "tag"
  }
]
```

See [fiddle](https://jsfiddle.net/remarkablemark/nzwLebtk/).

Then `html-react-parser` will try to create a React element based on the output:
```js
React.createElement('hello@world.com');
```

This throws an error, which is why React suggests wrapping the code in an error boundary.

So `try-catch` like you mentioned doesn't work here.

On a side note, I'm curious about your markup `<hello@world.com>`. It's not valid HTML nor is it valid XML. See [validation](https://www.xmlvalidation.com/) error:
```
Element type "hello" must be followed by either attribute specifications, ">" or "/>".
```

**Comment by gamesover** [comment]
when dom is created from string, you cannot guarantee the string is always valid.
It would be great that if this lib could catch the error, rather than leave it to user.

**Comment by remarkablemark** [comment]
Yes, in an ideal world it would be great to validate the markup. However, I made the decision not to do so as the tradeoff is too high in terms of performance cost and complexity.

Does that make sense @gamesover? Let me know what you think.

**Comment by gamesover** [comment]
absolutely. Thanks for your response @remarkablemark

**Comment by remarkablemark** [comment]
Let me know if there's anything else I can help you with. Otherwise, do you mind closing the issue?

**Comment by gamesover** [comment]
thanks for all the helps you are offered

**Comment by shanhexi** [comment]
可以用 sanitize-html 把 有害的标签剔除掉就可以了
