### ISSUE TITLE
Prevent parse of invalid html tags

### ISSUE THREAD

**Issue by nicoleCamoro** [remarkablemark/html-react-parser#124]
## Expected Behavior

Parser should ignore invalid html "tags".

## Actual Behavior

I receive this error in the console : 
`DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('someone@gmail.com') is not a valid name.`

## Steps to Reproduce
I'm parsing an email body and one of it's contents has this format: `<an,email@gmail.com>`

```js
var parse = require('html-react-parser');
parse("<p><someone@gmail.com></p>");
```

## Environment

- Version: 0.6.4
- Platform: Windows 10
- Browser: Google Chrome 77.0.3865.90

**Comment by remarkablemark** [comment]
Thanks for opening the issue @nicoleCamoro!

The error you get when trying to render an invalid tag is **expected** (see [fiddle](https://jsfiddle.net/remarkablemark/3a87qz9d/)).

`html-react-parser` (or to be exact, this library's dependency [`html-dom-parser`](https://github.com/remarkablemark/html-dom-parser)) does _not_ handle sanitizing HTML markup. This is because:

1. It goes beyond the scope of what this simple parser should do (see the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)),
2. Performing sanitization adds additional complexity (as well as bloat) to the package,
3. There are existing packages that do a terrific job sanitizing HTML so is there a reason to reinvent the wheel?

This leads to my question, which is are you able to use an HTML sanitization library? I.e., [`sanitize-html`](https://repl.it/@remarkablemark/sanitize-html) or [`dompurify`](https://repl.it/@remarkablemark/dompurify).

I created a [Repl.it](https://repl.it/@remarkablemark/html-react-parser-sanitize-html) that uses [`sanitize-html`](https://www.npmjs.com/package/sanitize-html) to sanitize your example. Also, there's a [Repl.it](https://repl.it/@remarkablemark/html-react-parser-dompurify) that uses [`dompurify`](https://www.npmjs.com/package/dompurify) to sanitize HTML (see #94).

Let me know if this helps answer your question.

**Comment by nicoleCamoro** [comment]
Oh I'm sorry I missed that. Your answer definitely helps. Thanks!
