### ISSUE TITLE
Window and document not defined in Webworker

### ISSUE THREAD

**Issue by alizeaiter** [remarkablemark/html-react-parser#130]
When using html-react-parser in Webworkers, window and document are not defined. You mentioned that it works also on Nodejs where window and dom are also not defined. How would one work around this.Thanks

**Comment by remarkablemark** [comment]
Great question @alizeaiter

The reason `html-react-parser` can be used in Node.js and in the browser is because of the dependency [`html-dom-parser`](https://github.com/remarkablemark/html-dom-parser), which is used to parse HTML string to DOM nodes.

In Node.js, `html-dom-parser` relies on [`htmlparser2`](https://github.com/fb55/htmlparser2); in the browser, `html-dom-parser` relies on the native browser API.

This is done to keep the bundle size small for the client. This is crucial because there is a direct correlation between bundle size and the time it takes to load it (as well as the cost it takes to serve it).

Now if you really wanted to include `htmlparser2` in the `html-dom-parser` build, you'll need to remove the ["browser" field](https://github.com/remarkablemark/html-dom-parser/blob/v0.2.3/package.json#L81-L83) and rebuild your bundle with `webpack` (or any other module bundler).

Otherwise, there should be other HTML to React parsers that can satisfy your needs.

I hope this answers your question.

**Comment by alizeaiter** [comment]
Thanks for your answer, I ended up using another parser that uses htmlparser2

**Comment by remarkablemark** [comment]
Sounds good! Closing the issue as it seems to be resolved.
