### ISSUE TITLE
html tag is being removed in certain conditions

### ISSUE THREAD

**Issue by taw1313** [remarkablemark/html-react-parser#170]
## Expected Behavior

render \<a> tag with a \<strong> child element

## Actual Behavior

"replace" is removing \<a> tag if it contains children with no whitespace between closing tags... I have created a simple example in Sandbox see below.

## Steps to Reproduce

```javascript 
import React, { Component } from "react";
import { render } from "react-dom";
import parse, { domToReact } from "html-react-parser";

import "./styles.css";

const options = {
  replace: ({ attribs, children }) => {
    if (!attribs) return;
    return domToReact(children, options);
  }
};

class App extends Component {
  render() {
    return (
      <div>
        {parse(
          '<a href="https://github.com"><strong>Broken</strong></a>',
          options
        )}
        <div />
        {parse(
          '<a href="https://github.com"><strong>Works</strong> </a>',
          options
        )}
      </div>
    );
  }
}

render(<App />, document.getElementById("root")); 
````

## Reproducible Demo
* CodeSandbox: https://codesandbox.io/s/html-react-parser-6mtxp?file=/src/index.js

## Environment

- Version:  html-react-parser 0.11.1 ( reproduced in 0.13.0 )
- Platform: react 16.9
- Browser: chrome, edge, etc...

**Comment by remarkablemark** [comment]
Thanks for opening this issue. `replace` is working as expected. `<a>` is not being parsed because you forgot to include it in `domToReact()`.

So instead of passing the children:

```jsx
const options = {
  replace: ({ attribs, children }) => {
    if (!attribs) return;
    return domToReact(children, options);
  }
};
```

You want to pass the parent:

```jsx
const options = {
  replace: domNode => {
    const { attribs } = domNode;
    if (!attribs) return;
    return domToReact(domNode, options);
  }
};
```

The reason your 2nd example worked is probably due to a bug in [html-dom-parser](https://github.com/remarkablemark/html-dom-parser).

See [CodeSandbox](https://codesandbox.io/s/html-react-parser-170-pehir) with both examples working.

**Comment by taw1313** [comment]
Thank you...  works as you expect...
