### ISSUE TITLE
For TS projects, instanceof is always returning false

### ISSUE THREAD

**Issue by syedfarathsayeed** [remarkablemark/html-react-parser#204]
I have a htmlString to parse and would like to customize some elements after parsing, thus using replace function.

But instanceof Element is always returning false.

I have created a demo https://codesandbox.io/s/priceless-thunder-u14q2?file=/src/App.tsx

In the console if you see, I do have a Element instance, but its still returning false for an instanceof check

**Comment by remarkablemark** [comment]
Thanks for opening the issue @syedfarathsayeed!

The reason why `domNode instanceof Element` is always returning false is because the incorrect `Element` is used. Instead of using the DOM Element, please use the [domhandler](https://github.com/fb55/domhandler) Element:

```tsx
import { Element } from 'domhandler/lib/node';
```

See [CodeSandbox](https://codesandbox.io/s/html-react-parser-204-59uyn?file=/src/App.tsx) or [README](https://github.com/remarkablemark/html-react-parser/tree/v1.1.1#v100).

**Comment by syedfarathsayeed** [comment]
Thanks for your reply.
