### ISSUE TITLE
Can't make `lowerCaseTags` work properly

### ISSUE THREAD

**Issue by undavide** [remarkablemark/html-react-parser#206]
## Expected Behavior

I'm trying to pass in the parsed string a React Component, so I've set
```
const options = {
    htmlparser2: {
      lowerCaseTags: false,
    },
  };
```

to prevent `parse()` to output a lowercase tag

## Actual Behavior

The tag is rendered lowercase nonetheless.

## Reproducible Demo

See [this CodeSandbox](https://codesandbox.io/s/html-react-parser-forked-lrkzv?file=/src/index.js)

I've imported `{Link as SpectrumLink}` but in the page it's rendered as `<spectrumlink>` anyway – in fact the Console complains that:
> Warning: The tag <spectrumlink> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

## Environment

- Version: 1.1.1
- Platform: macOS 10.15.7
- Browser: Chrome 87.0.4280.88

Thanks!!

**Comment by undavide** [comment]
FWIW,
I've worked around with a `replace` function that wraps `<a>` tags with Spectrum `<Link>`, see [the CodeSandbox](https://codesandbox.io/s/html-react-parser-forked-nehpm?file=/src/index.js).

**Comment by remarkablemark** [comment]
Thanks for opening the issue @undavide.

This is expected behavior since `htmlparser2` options only work on the server-side (Node.js) and do not work on the client-side (browser).

**Comment by undavide** [comment]
Oh, thanks!
I don't know if this is related – possibly, I'm a bit overwhelmed by Gatsby at the moment – but I also had other issues due to the fact that I wasn't properly _"hydrating"_ the Server Side Rendering. React Spectrum has this `<SSRProvider>` component that I missed, adding that back solved my other problems.
I've also discovered that with the Gatsby version I've been using:

> Hydration problems didn't happen in dev in the past as we didn't SSR

Which maybe explain why the `html-react-parser` component worked fine on dev and broke on production? Just guessing.

**Comment by jerelmiller** [comment]
I actually ran into this exact issue. I'd love to be able to maintain casing for tag names and attribute names. Unfortunately these options are ignored client-side.

I want to be able to selectively replace specific bits of a string with React components. The text itself could be XML/HTML, or any other language. I want to keep the XML nodes stringified as raw text (which I can do myself), but replace specific nodes with React components. This is to allow rich formatting inside code blocks. Since the XML nodes need to remain stringified, they need to keep their casing as they are displayed in the code block to the end user.

As an example, here is a block of XML that we show to the end user:

```
<dependency>
  <groupId>com.library.agent.java</groupId>
  <artifactId>library-java</artifactId>
  <version><var>JAVA_LIBRARY_VERSION</var></version>
  <scope>provided</scope>
  <type>zip</type>
</dependency>
```

I want to replace the `<var>` tag with an actual React `var` element, but keep the other text as-is.

> Let me know if the documentation is not clear.

I'd definitely say this could use a bit more clarification. I didn't realize `htmlparser2` wasn't being used on the client until reading this issue.

**Comment by remarkablemark** [comment]
@jerelmiller If you want to continue to use `htmlparser2` on the client-side, you will need to do some webpack finagling to ensure it gets loaded there (see [html-dom-parser](https://github.com/remarkablemark/html-dom-parser/blob/v1.0.0/package.json#L80)). The downside is that it will greatly increase your bundle size.

In regards to `README.md` documentation, would you like to open a PR to make it clearer?
