### ISSUE TITLE
Unable to parse css styles which contain !important

### ISSUE THREAD

**Issue by Marko-Matijevic** [remarkablemark/html-react-parser#284]
## Expected Behavior
Styles with important should be applied to parsed HTML

## Actual Behavior
HTML which contains style rule with !important does not get applied after parsing

## Steps to Reproduce

Create a HTML inside a string which contains style rule with !important;
`const html = 
      <h1 style="display: none !important;">
        html-react-parser
      </h1>;`

After using:
`parse(html)`
H1 element with text html-react-parser will be displayed

## Reproducible Demo
https://jsfiddle.net/e87hqu3s/2/

## Environment

- Version: Latest version
- Platform: Windows 10
- Browser: Chrome

**Comment by remarkablemark** [comment]
Thanks for opening the issue @Marko-Matijevic!

This is expected behavior since React considers inline style value with `!important` invalid since

```html
<h1 style="display: none !important;">html-react-parser</h1>
```

gets parsed into

```jsx
<h1 style={{ display: 'none !important' }}>html-react-parser</h1>
```

See [JSFiddle](https://jsfiddle.net/remarkablemark/w1psyt6h/).

My recommendation is to use [replace](https://github.com/remarkablemark/html-react-parser/tree/v1.4.2#replace) to remove `!important`.
