### ISSUE TITLE
Ability to pass options to htmlparser2

### ISSUE THREAD

**Issue by chrisbateman** [remarkablemark/html-react-parser#34]
In order to set set `decodeEntities` to true, for example.

I think that the call to `htmlToDOM` on this line just needs to pass in a 2nd parameter with options: https://github.com/remarkablemark/html-react-parser/blob/master/index.js#L21

**Comment by remarkablemark** [comment]
That's a good point.

If `decodeEntities` is true by default, then would passing options to `htmlparser2` still be a desirable feature?

**Comment by chrisbateman** [comment]
That's the only one I needed.

htmlparser does have some other options though: https://github.com/fb55/htmlparser2/wiki/Parser-options

**Comment by remarkablemark** [comment]
For now, I will set `decodeEntities` to true by default and when the use-case for setting additional options arises, I'll then decide how the feature should be added.

My rationale for this is because `html-react-parser` is an isomorphic library so if the parsing were to change on node, then I need to ensure that the same change occurs on the browser (`htmlparser2` is not loaded nor used on the client as there's no need).
