### ISSUE TITLE
attribs

### ISSUE THREAD

**Issue by smiile** [remarkablemark/html-react-parser#54]
Hello, thanks for the great library!

I was wondering about your choice in abbreviating attributes as `attribs`. It's not standard and not easily recognizable (the only thing it reminds me of is ribs, which I love, but are unrelated).
Most of the project I've used, if abbreviating at all, which is becoming more rare these days, use `attr` and `attrs`.

Conventions are cool because they provide mental framework, so we don't spend extra attention and effort to reinvent the wheel, or recognize it as such

Thanks,
Wish you all the best

**Comment by remarkablemark** [comment]
Hi @smiile, I appreciate the feedback!

The reason attributes is abbreviated as `attribs` because this library uses [htmlparser2](https://github.com/fb55/htmlparser2) and that's what htmlparser2 does.

So I don't think htmlparser2 will be renaming the property key any time soon and if they do, it will be a breaking change for all of us.

Although I could add another property named `attributes` to the object, I'm not a fan of that approach because (1) it's redundant and (2) it will most likely impact performance.

**Comment by remarkablemark** [comment]
Hey @smiile, do you have any other thoughts on this matter? If not, I'll be closing this issue. Thanks!

**Comment by smiile** [comment]
Hey @remarkablemark, for the sake of argument I'd like to add that having an additional getter wouldn't impact performance, but I haven't checked if you use the appropriate ES version for that. Given that I'm the only one who's bothered by that and it's a code style comment I agree on closing the issue. Thanks for your extensive reply on it

**Comment by remarkablemark** [comment]
You're very welcome. Thanks for taking the time to bring this point up in the first place too!
