### ISSUE TITLE
Input default values

### ISSUE THREAD

**Issue by k1sul1** [remarkablemark/html-react-parser#63]
I've used this package as a peer dependency for react-libre-form, and we're currently using it in a "large scale" React application. Great work on it! 

The issue is about react-libre-form, kinda. It's a React component for WP Libre Form,  a form plugin for WordPress that let's you have 100% control of the markup.

So this is my problem. Say I get this chunk of HTML from the WP REST API:

```
<input type="text" name="name" id="fb-name" placeholder="Matti Meikäläinen" defaultValue="Oispa kaljaa">
```

In this case, defaultValue has been prefilled from the user details. But when I ran this through the parser, the input appears, but the default value is nowhere to be seen. 

If I change defaultValue into value, it "works", except the usual React yadda yadda about not specifying an input handler. 

```
<input type="text" name="name" id="fb-name" placeholder="Matti Meikäläinen" value="Oispa kaljaa">
```

The thing is, I'd rather have them as uncontrolled inputs, and don't want to use the value attribute.  I'm guessing the defaultValue is a JSX thing and that's why it doesn't work. 

But do I have any options, other than adding a input handler?

**Comment by remarkablemark** [comment]
You are correct in that `defaultValue` is not a native DOM element attribute but a React-specific prop for elements.

But the reason why the `defaultValue` is not passed to your React element is because the attribute gets lowercased when transforming from HTML string to DOM nodes. Then when the DOM nodes get transformed to React elements, it gets lost in the way because it's invalid.

Hence, one approach is to use the `replace` option to create the input React element correctly: https://repl.it/@remarkablemark/html-react-parser-issue-63

**Comment by k1sul1** [comment]
I like it. We're heavily using the replace function anyway, so this is a perfect fix. 

I'd add this to the README so you don't have to answer the same question again.

**Comment by k1sul1** [comment]
It works. 

https://github.com/libreform/react-libre-form/blob/8f7dfa12b6da8bf364c68d851f97ff770c95a25c/src/index.js#L85

Cheers.
