### ISSUE TITLE
Loosing onclick functionality after parse

### ISSUE THREAD

**Issue by jasan-s** [remarkablemark/html-react-parser#73]
see https://jsfiddle.net/kvgz36eh/.

notice that the onclick methods are lost post parsing , thus on click the hidden input field value is never updated.

**Comment by remarkablemark** [comment]
Thanks for opening the issue @jasan-s

The `onclick` not being set on the React element is actually expected behavior. (A similar issue was brought up in #53.)

Because there's an XSS security risk when evaling the `onclick` string, the property is not translated in the [HTMLDOMPropertyConfig](https://github.com/facebook/react/blob/15-stable/src/renderers/dom/shared/HTMLDOMPropertyConfig.js) map.

The best solution is to use the [`replace`](https://github.com/remarkablemark/html-react-parser#replacedomnode) option. See updated [fiddle](https://jsfiddle.net/remarkablemark/kvgz36eh/1/).

**Comment by jasan-s** [comment]
@remarkablemark  thanks for that,  I realized the intentional removal of dirty html afterward. I solved it using the following :
`const answer = document.querySelector('input[name="otpselection"]:checked').value;`
although i like your solution as well.

**Comment by kasvith** [comment]
@remarkablemark i think there should be an option for bypassing this. when a trusted backend sends html code, its much needed to handle event listners automatically

**Comment by remarkablemark** [comment]
@kasvith the recommended approach is to use the `replace` option. If you have any questions, feel free to open a new discussion or issue.
