### ISSUE TITLE
Boolean attributes on custom components

### ISSUE THREAD

**Issue by hk86** [remarkablemark/html-react-parser#757]
First of all, this is a great package, exactly what I was looking for!

I've got a headless CMS to maintain my content. That content can contain custom components, these tags are replaced when the content is parsed by `html-react-parser`.

In my content I have then tags like `<CustomComponent tier="3" ordered />`

I then replace the tags with the React component and use `attributesToProps`. Everything works fine except that the attribute `ordered` is not replaced by a boolean value, but by an empty string. I have a workaround to set the property correctly in my `replace` function:

```
const props = attributesToProps(domNode.attribs);
return <CustomComponent {...props} ordered={props.ordered=== ''} />
```

Not sure whether this is expected or maybe there is a better way?

**Comment by remarkablemark** [comment]
Thanks for opening this issue @hk86. This is expected behavior as empty attribute syntax is equivalent to specifying an empty string as the value for the attribute. See https://stackoverflow.com/questions/9729080/are-empty-html5-data-attributes-valid#answer-23752239

Let me know if this answers your question.

**Comment by hk86** [comment]
Yes this answers my question. Thanks.
