### ISSUE TITLE
list value is not preserved while parsing and rendering in UI.

### ISSUE THREAD

**Issue by Vinay-Kurapati** [remarkablemark/html-react-parser#839]
## Expected Behavior
When a list item has a value attribute, the value is not preserved parsing and rendering in UI.
 Ex:  <ol><li value="3">Item-3</li></ol>

## Actual Behavior
It should preserve the list value. 
1. Item-3

## Steps to Reproduce
Please check the below link

## Reproducible Demo
https://codesandbox.io/s/loving-violet-2gicem?file=/src/App.js

## Environment
- Version: 3.0.9

**Comment by remarkablemark** [comment]
Thanks for opening this issue @Vinay-Kurapati. I can reproduce this bug in your [demo](https://codesandbox.io/s/html-react-parser-839-sb8c5g). The root cause is from this line: https://github.com/remarkablemark/html-react-parser/blob/v3.0.10/lib/attributes-to-props.js#L50

The attribute `value` is being transformed to `defaultValue`:

![Screen Shot 2023-03-03 at 8 20 42 PM](https://user-images.githubusercontent.com/10594555/222867968-7072efd5-2212-4309-8a71-b021db222fe7.png)

Would you be interested in opening a PR for the fix?

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/853#issuecomment-1454845349
